name: 'Install Puppet'
description: 'Install Puppet Workstation'
runs:
  using: "composite"
  steps:
    - name: Install Puppet
      id: install
      run: ${{ github.action_path }}/install.sh ${{ inputs.version }}
      shell: bash
