on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Tests

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        uses: newrelic/infrastructure-agent-puppet/.github/actions/installation@github_actions
      - name: Run pdk validate
        uses: newrelic/infrastructure-agent-puppet/.github/actions/tests@github_actions
